### PR TITLE
add note regarding setParams and torque

### PR DESCRIPTION
**Pull request by csobier**
@rochoa , created this note based on a Support request to add this known issue to the docs.

Please approve?  
(If approved, I'll also add the same note to the CartoDB.js / layer.setParams() description).

### CODE REVIEW

**Comment by rochoa** [comment]
Shouldn't this be just at cartodb.js' documentation? It's a limitation of that library.

I would start by creating an issue at cartodb.js to see if we can make setParams to work with torque layers.

**Comment by csobier** [comment]
As you wish!  See https://github.com/CartoDB/cartodb.js/issues/1035

Please advise.  If the issue will not be implemented anytime soon, we really should document this known issue in all relevant areas (Named Maps & CartoDB.js).

**Comment by csobier** [comment]
@rochoa , Javi Santana told me to merge the CartoDB.js doc note yesterday. For consistency, we should also add the same note to the Named Map doc (until the issue is fixed). Okay if I merge this note now?

**Comment by csobier** [comment]
ping!

**Comment by rochoa** [comment]
Let's do it!

**Pull request merged**
