### PR TITLE
Add table base _vovw_count and fix tests for count support

### PR DESCRIPTION
**Pull request by iriberri**
Closes https://github.com/CartoDB/Windshaft-cartodb/issues/413

* Add "1 AS _vovw_count" in query rewrites for the base table SELECT
* Fixes tests to support the new `_vovw_count`

cc @jgoizueta

### CODE REVIEW

**Comment by jgoizueta** [comment]
👍

**Comment by iriberri** [comment]
Hey @dgaubert could you review, please? :-)

**Comment by dgaubert** [comment]
:+1:

**Comment by iriberri** [comment]
As I mentioned in the issue, we're not going to use this approach as we finally don't need any change in this project, so closing without merging. Thanks all!

**Pull request closed without merging**
