### PR TITLE
Docs minor clarification added

### PR DESCRIPTION
**Pull request by csobier**
Applying new links for mapconfig and minor text edits.

### CODE REVIEW

**Comment by csobier** [comment]
@rochoa , please let me know if I can go ahead and merge these minor edts?

**Comment by rochoa** [comment]
Can we use full URLs? That way they also work if you are seeing the files in GitHub or in your text editor.

**Comment by csobier** [comment]
We can ask @matallo?
(He has always instructed me to create links as shown, but I'm willing to adapt)

**Comment by csobier** [comment]
@matallo , I was proactive and applied absolute paths for the URL's, as per Raul's request. Will you allow this so that we can merge?

**Comment by matallo** [comment]
:rocket:

**Comment by csobier** [comment]
@matallo , can you help? This was appearing live yesterday but now it's not?

**Pull request merged**
