### PR TITLE
Add suport for WHERE clauses in overview queries

### LINKED ISSUE #428: Allow basic filtering in overviews queries
Currently when (vector) overviews exist for a table, they're used in the query passed to Mapnik only if the original query is of a very simple form not having a WHERE clause.

Allow the queries to have a simple (no joins, subselections, etc.) WHERE clause and apply it to the query passed to the tiler.

### PR DESCRIPTION
**Pull request by jgoizueta**
Fixes #428

### CODE REVIEW

**Comment by jgoizueta** [comment]
@rochoa can you review (or invite someone to) this? cc @rafatower

**Comment by rochoa** [comment]
At some point we should start considering https://github.com/lfittl/pg_query as the alternative to this regex solution.

**Comment by rochoa** [comment]
Understanding and maintaining this will get crazy otherwise.

:shipit:

**Comment by jgoizueta** [comment]
I was thinking the same. Actually I did some testing with pg_query some time ago.

**Comment by rochoa** [comment]
BTW, I'm missing the point of this PR. What do we want to achieve with it?

**Comment by jgoizueta** [comment]
I did it with the intention of allowing filters (e.g. from the editor), but I'm focus now on having overviews work with widgets (so that filters applied by widgets apply to overviews visualization and so that overviews can by used by the dataviews used in widgets).

This approach is useless for those purposes, so I'm closing this now.

**Pull request closed without merging**
