### PR TITLE
Documentation for named maps static images + view option in templates

### PR DESCRIPTION
**Pull request by rochoa**
- information about named maps static image endpoint
 - new `view` element in named maps templates

### CODE REVIEW

**Comment by ohasselblad** [comment]
Looks great to me! :eggplant: :tomato: :tofu:

**Comment by ohasselblad** [comment]
Do you want me to do any tests on the views parameters?

**Comment by rochoa** [comment]
If you can play around a bit it would be awesome! :poultry_leg: :beer: :smile:

**Comment by rochoa** [comment]
@ohasselblad Did you get the time to test it a bit?

**Comment by ohasselblad** [comment]
I can do some testing today!

On Mon, Jun 8, 2015 at 10:07 AM, Raul Ochoa <notifications@github.com>
wrote:

> @ohasselblad <https://github.com/ohasselblad> Did you get the time to
> test it a bit?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/Windshaft-cartodb/pull/304#issuecomment-110007358>
> .
>



-- 
Andy Eschbacher
Map Scientist
CartoDB <http://cartodb.com>
eschbacher@cartodb.com

**Comment by rochoa** [comment]
If you find the documentation part OK I prefer to merge it and later create new issues if you find any problem, does that work for you?

**Comment by ohasselblad** [comment]
Yep, fine with me!

**Pull request merged**
