### PR TITLE
Optimize overviews queries

### PR DESCRIPTION
**Pull request by jgoizueta**
The PostgreSQL planner wasn't applying the spatial filtering of
tile bounds to the queries efficiently.

### CODE REVIEW

**Comment by jgoizueta** [comment]
@rochoa @rafatower please CR this

**Comment by rafatower** [comment]
:+1: in the previous form the query planner was doing a full scan instead of taking advantage of the gist index

**Comment by rafatower** [comment]
the problem with travis builds:

**Comment by jgoizueta** [comment]
It seems tha travis is not taking not of `postgresql: "9.4"` and 9.1 is running: if I add the `postgresql-9.4` package:

```
Setting up postgresql-9.4 (9.4.6-1.pgdg12.4+1) ...
Refused to start PostgreSQL 9.4, because PostgreSQL 9.1 is currently running! You should first stop 9.1 instance...
invoke-rc.d: initscript postgresql, action "start" failed.
dpkg: error processing postgresql-9.4 (--configure):
 subprocess installed post-installation script returned error exit status 13
```

**Comment by rochoa** [comment]
It seems like a bug/issue at travis with addons. I just did a PR to go back to `sudo: true`. Builds start time will be way slower but at least it's functional.

Meanwhile I'm gonna open an issue at travis repo.

**Comment by rochoa** [comment]
PR is https://github.com/CartoDB/Windshaft-cartodb/pull/393

**Pull request merged**
