### PR TITLE
Update instructions

### PR DESCRIPTION
**Pull request by juanignaciosl**
@rochoa maybe you think this is pointless, maybe not :_)

### CODE REVIEW

**Comment by rochoa** [comment]
While I agree we should provide some kind of information about upgrading: that's not universal because not every time you upgrade you need to reinstall all dependencies.

Using:
```shell
make clean all
```

Equals:

```shell
rm -rf node_modules; npm install
```

[NEWS.md](https://github.com/CartoDB/Windshaft-cartodb/blob/2.5.0/NEWS.md) contains information about upgraded dependencies.

Anyway, as I said, I'm OK because we need to provide some information, but can we change the `pull master branch` to something less specific: `checkout your commit/branch` or something similar.

**Comment by juanignaciosl** [comment]
@rochoa :eyes:

**Comment by rochoa** [comment]
:+1:

**Comment by rochoa** [comment]
Thanks!

**Pull request merged**
