### PR TITLE
Add `no_filters` param to dataviews

### PR DESCRIPTION
**Pull request by ivanmalagon**
Related to https://github.com/CartoDB/Windshaft-cartodb/issues/776
----

This PR adds the query param `no_filters` to the dataview URL in order to get the data with no filters applied.

### CODE REVIEW

**Comment by dgaubert** [comment]
What if I request a dataview's result with `own_filter=1` and `no_filters=1`? 

If I'm not wrong, the current implementation returns a dataview without filters. Is that the expected behavior??

**Comment by ivanmalagon** [comment]
If both params are present, `no_filters` prevails and `own_filter` is discarded.

For me, that's the expected behaviour since it's a stronger condition.

**Comment by dgaubert** [comment]
Let me be a PITA.

I don't agree. I understand your point but it's confusing to the user's point of view. We have two different params (`no_filters` and `own_filter`) for the same thing: to choose the dataview's query. The fact of having two different params was for being more user-friendly, giving priority to them it's confusing.

I'd validate when both of them are present and respond with error:
```
if (Number.isFinite(ownFilter) && Number.isFinite(noFilters)) {
  const error = new Error('Bad query params ....');
  error.http_status = 400
  return callback(error);
}
```

**Comment by ivanmalagon** [comment]
Can you take a look on the commit https://github.com/CartoDB/Windshaft-cartodb/pull/809/commits/02ac25181e58084937bc46509f640775c8e6e97f ?

I've added a `type='dataview'` to get a better context to tackle the error in Builder, but I haven't found any other appearance of it. So if there's a better type for the dataview let me know. (didn't fell the `unknown` type)

**Pull request merged**
