### PR TITLE
Fix error context, replaced `turbo-carto` error type by `layer` type

### PR DESCRIPTION
**Pull request by dgaubert**
errors with context, analysis type:
```js
{ 
  errors_with_context: [{
    type: 'analysis',
    message: 'Missing required param "radius"',
    analysis: { id: 'HEAD', type: 'buffer' } 
  }]
}
```
layer type:
```js
{
  errors_with_context: [{
    type: 'layer',
    message: 'turbo-carto: Unable to process "marker-fill". Reason: Unable to compute ramp. Reason: column "wadus_column" does not exist. Context: {"selector":"#populated_places_simple_reduced","source":{"start":{"line":10,"column":3},"end":{"line":10,"column":56}}}',
    http_status: 400,
    layer: {
      index: 0,
      type: 'mapnik',
      context: {
        selector: '#populated_places_simple_reduced',
        source: {
          start: {
            line: 10,
            column: 3
          },
          end: {
            line: 10,
            column: 56
          }
        }
      }
    }
  }]
}
```

please @alonsogarciapablo & @rochoa CR.

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
👍 I don't think I'll use the `http_status: 400` and `.layer.context` for now though. I'd merge this so that I can implement the CartoDB.js part, and the we can iterate.

**Comment by dgaubert** [comment]
I kept `http_status` because of backwards compatibility and `.layer.context` could be useful if we want to highlight the error in cartocss editor.

**Comment by rochoa** [comment]
I don't like this one. How do I know it's a turbo-carto/cartocss error?

**Comment by dgaubert** [comment]
Did you mean to use a `type: "analysis"` instead of `turbo-carto`? To me is indifferent, I'll use what you decide. What are your thoughts @alonsogarciapablo?

**Comment by alonsogarciapablo** [comment]
> I don't like this one. How do I know it's a turbo-carto/cartocss error?

This is probably when error codes can come in handy. What do you think?

**Comment by alonsogarciapablo** [comment]
I talked with @rochoa offline about this.

```
{ 
  errors_with_context: [{
    type: 'analysis',
    message: 'Missing required param "radius"',
    analysis: { id: 'HEAD', type: 'buffer' } 
  }]
}
````

☝️ is perfect for now.

```
{
  errors_with_context: [{
    type: 'layer',
    message: 'turbo-carto: Unable...',
    layer: {
      index: 0,
      type: 'mapnik',
      context: {
        selector: '#populated_places_simple_reduced',
        source: {
          start: {
            line: 10,
            column: 3
          },
          end: {
            line: 10,
            column: 56
          }
        }
      }
    }
  }]
}
```

About :point_up: we both agree that `type: 'layer'` is a good idea, but the editor will need to "categorise" these errors a bit more so we might need to add a sub-type somewhere (eg: `turbo-carto`, `sql`, you name it!). I'll think about this a bit more. @dgaubert  suggestions are welcome!

Also, we agreed that it'd be great to replace the `index` by the `id` of the layer, as suggested in a previous comment. We can start changing this!

**Comment by dgaubert** [comment]
that's how it looks right now:

```js
{
  errors_with_context: [{
    type: 'layer',
    subtype: 'turbo-carto',
    message: 'turbo-carto: Unable...',
    layer: {
      id: 'layer0',
      index: 0,
      type: 'mapnik',
      context: {
        selector: '#populated_places_simple_reduced',
        source: {
          start: {
            line: 10,
            column: 3
          },
          end: {
            line: 10,
            column: 56
          }
        }
      }
    }
  }]
}
```
@alonsogarciapablo & @rochoa, that's fine for now, isn't it?

**Comment by alonsogarciapablo** [comment]
Looks good to me! I'd remove `layer.index` since we don't actually need it right now.

**Comment by rochoa** [comment]
I would keep layer index so it covers when you don't send an id for the layer.

**Comment by alonsogarciapablo** [comment]
Ok, but just to be clear, for our current use case (editor + cartodb.js) I'm planning to work with the ids.

**Pull request merged**
