### PR TITLE
Add Mapnik 'cache-features' option

### PR DESCRIPTION
**Pull request by Algunenano**

### CODE REVIEW

**Comment by rafatower** [comment]
> Note this would require changing the configuration in the production machines in order to actually enable the cache-features setting.

Actually, as Raul pointed out to me, the behavior in Windshaft is to have `cache-features` enabled by default. So a config change is not required but could be disabled, if ever needed.

**Comment by rafatower** [comment]
PS: you'll need to `yarn install` and then commit and push the `yarn.lock` as there are changes in the dependencies.

**Comment by Algunenano** [comment]
Added a commit to update `yarn.lock`.

**Comment by Algunenano** [comment]
Switched to `5.3.3` instead so it doesn't allow setting the option though Mapconfig.

**Pull request merged**
