### PR TITLE
Fix docs reference

### PR DESCRIPTION
**Pull request by jgoizueta**
The external MapConfig docs filename is going to be changed

### CODE REVIEW

**Comment by dgaubert** [comment]
Hey @jgoizueta,

This PR is still alive? Or the new developer center supersedes these changes?

**Comment by jgoizueta** [comment]
Sorry, I had missed this. Yes this should be done.

**Comment by dgaubert** [comment]
Shall we merge it?

**Comment by csubira** [comment]
Closed by https://github.com/CartoDB/Windshaft-cartodb/pull/879

**Pull request closed without merging**
