### PR TITLE
Upgrade camshaft to 0.46.0

### PR DESCRIPTION
**Pull request by jgoizueta**
The new version of camshaft requires a CDB_CheckAnalysisQuota function
to check analysis cache quota.

### CODE REVIEW

**Comment by rochoa** [comment]
😮  How did you generate the npm-shrinkwrap?

**Comment by jgoizueta** [comment]
with `npm install --no-shrinkwrap && npm shrinkwrap` and I was just wandering about the weird changes in it

**Comment by jgoizueta** [comment]
@rochoa can review/approve? (and put it into the next release 😁 )

**Comment by rochoa** [comment]
Thank you @jgoizueta! 🎉

**Pull request merged**
